on:
  push:
name: Build and Test on Push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run gello action
        env: 
          SECRET_HOGE_2: ${{ secrets.KEY_TEST }}
        run: echo $SECRET_HOGE_2